# Site settings

baseurl: "" # the subpath of your site, e.g. /portfolio
url: "" # the base hostname & protocol for your site
language: "" # language to set into html tag, default is en

# User settings

author: Ezequiel França
author-title: iOS Developer
gravatar: d36a082aacb53b6f76869748fb4b81d4
email: ezefranca.br@gmail.com
twitter: ezefranca
github: ezefranca
facebook: ezefranca
linkedin: ezefranca/en
bio: "Brazilian iOS developer.

# Skills
#
# I'll use five differents levels:
# 1 - Studying: You know the basics of the skill and is studying it to get better
# 2 - Padawan: You know a little more than the basics and is comfortable to work with it
# 3 - Work with: You know how to handle the skill and how to properly use it in a real project
# 4 - Specialist: You have advanced knowledge of the skill and know how to use its best practices in a real project
# 5 - Jedi: You master the skill, know how and when to use and when not use it
#
# You can change these names in _includes/_skill-level-name.html if you wish
#
# If you don't want one of the sections below, leave the variable without any values

mobile:
  - name: iOS
    level: 3
db:
  - name: CoreData
    level: 3
  - name: Realm
    level: 3
  - name: SQLite
    level: 3
  - name: Firebase
    level: 3
    
devops:

  - name: Git
    level: 4
  - name: Continuous Integration
    level: 1
  - name: Continuous Delivery
    level: 1

methodologies:
  - name: Agile Methodologies
    level: 3
  - name: Scrum
    level: 4
  - name: RUP
    level: 3

# Build settings

markdown: kramdown
highlighter: rouge
sitemap: true # Generate sitemap.xml

sass:
  sass_dir: css
  style: compressed
## For more settings: https://jekyllrb.com/docs/configuration/

# exclude files if no need build
exclude: ['package.json', 'node_modules', 'README.md', 'LICENSE']

# Gems
gems: [jekyll-sitemap]
